/*
 * Stoatworks Labs - About window data for Flipdot.
 *
 * PROVISIONAL HAND COPY, 2026-09-25. In a registered repo this file is
 * GENERATED by stoatworks-backend/scripts/sync-about.py from the website's
 * projects.json. Flipdot is not registered yet, so this was adapted by hand
 * from splitflap's generated copy, with `guide` empty because no user guide
 * exists (an empty link is left out of the About buttons rather than shown as
 * a 404). Register the project and re-run the sync before the first release;
 * it will overwrite this file, and Flipdot.cpp's static_assert will then ask
 * for a fourth About button.
 *
 * `version` here is a fallback read from this repo's own manifest at sync
 * time. Anything with a build step injects the real one at build time and
 * overrides this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Flipdot";
    inline constexpr auto slug = "flipdot";
    inline constexpr auto hook = "An electromagnetic flip-dot sign, for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/flipdot/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/flipdot";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
